#!/bin/bash

set -euo pipefail

date >> /tmp/renew-log

echo "Deploying certs to mosquitto"

find /etc/mosquitto/certs -type f -print0 | xargs --no-run-if-empty -0 rm
cp -Lr /etc/letsencrypt/live/dlock-dev.trygvis.io/* /etc/mosquitto/certs
chown -R mosquitto:mosquitto /etc/mosquitto/certs
chmod u=r /etc/mosquitto/certs/*
