---
- name: Mobile network connection
  tags: mobile-network
  block:
    - name: Install system dependencies
      apt:
        name:
        - network-manager
        - modemmanager
        - python-dbus
        - gir1.2-networkmanager-1.0
    - name: Add NetworkManager connection
      shell: "nmcli connection show mobile || nmcli connection add con-name mobile type gsm ifname '*' apn {{mobile_network_apn}}"
    - name: Configure connection
      command: "nmcli connection modify mobile connection.autoconnect yes connection.autoconnect-retries 1000 gsm.pin {{mobile_network_pin}} gsm.number {{mobile_network_number}}"
    - name: Set connection as up
      command: "nmcli connection up mobile"
      ignore_errors: yes # will happen if GSM modem not plugged in
